DefaultContentLanguage = "en"
Paginate = 3
SectionPagesMenu = "main"
baseURL = "https://extraordinary-dango-6abd57.netlify.app"
enableRobotsTXT = true
googleAnalytics = ""
languageCode = "en-us"
resourceDir = "../resources"
theme = "ananke"
title = "Notre-Dame de Paris"
[languages.en]
contentDir = "content/en"
title = "Ananke"
weight = 1
[languages.fr]
contentDir = "content/fr"
title = "Ananke Fr"
weight = 2
[params]
author = ""
background_color_class = "bg-black"
description = "The last theme you'll ever need. Maybe."
favicon = ""
recent_posts_number = 3
site_logo = "/images/image-logo.jpg"
text_color = ""
[[params.ananke_socials]]
name = "twitter"
url = "https://twitter.com/GoHugoIO"
[sitemap]
changefreq = "monthly"
filename = "sitemap.xml"
priority = 0.5
